### ISSUE TITLE
mvn package failed

### ISSUE THREAD

**Issue by silenceper** [Graylog2/graylog-plugin-collector#62]
>mvn package 

file：graylog-plugin-collector/target/surefire-reports
content:

```
-------------------------------------------------------------------------------
Test set: org.graylog.plugins.collector.collectors.CollectorServiceImplTest
-------------------------------------------------------------------------------
Tests run: 10, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 6.299 sec <<< FAILURE! - in org.graylog.plugins.collector.collectors.CollectorServiceImplTest
testFindByNodeId(org.graylog.plugins.collector.collectors.CollectorServiceImplTest)  Time elapsed: 0.564 sec  <<< ERROR!
org.mongojack.MongoJsonMappingException: Error mapping BSON to POJOs
	at org.graylog.plugins.collector.collectors.CollectorServiceImplTest.testFindByNodeId(CollectorServiceImplTest.java:140)
Caused by: com.fasterxml.jackson.databind.JsonMappingException:
Can not construct instance of org.graylog.plugins.collector.collectors.CollectorNodeDetails, problem: Unresolved compilation problem:
	AutoValue_CollectorNodeDetails cannot be resolved to a type

 at [Source: N/A; line: -1, column: -1] (through reference chain: org.graylog.plugins.collector.collectors.CollectorImpl["node_details"])
	at org.graylog.plugins.collector.collectors.CollectorServiceImplTest.testFindByNodeId(CollectorServiceImplTest.java:140)
Caused by: java.lang.Error:
Unresolved compilation problem:
	AutoValue_CollectorNodeDetails cannot be resolved to a type

	at org.graylog.plugins.collector.collectors.CollectorServiceImplTest.testFindByNodeId(CollectorServiceImplTest.java:140)

testAll(org.graylog.plugins.collector.collectors.CollectorServiceImplTest)  Time elapsed: 0.044 sec  <<< ERROR!
org.mongojack.MongoJsonMappingException: Error mapping BSON to POJOs
	at org.graylog.plugins.collector.collectors.CollectorServiceImplTest.testAll(CollectorServiceImplTest.java:99)
Caused by: com.fasterxml.jackson.databind.JsonMappingException:
Can not construct instance of org.graylog.plugins.collector.collectors.CollectorNodeDetails, problem: Unresolved compilation problem:
	AutoValue_CollectorNodeDetails cannot be resolved to a type

 at [Source: N/A; line: -1, column: -1] (through reference chain: org.graylog.plugins.collector.collectors.CollectorImpl["node_details"])
	at org.graylog.plugins.collector.collectors.CollectorServiceImplTest.testAll(CollectorServiceImplTest.java:99)
Caused by: java.lang.Error:
Unresolved compilation problem:
	AutoValue_CollectorNodeDetails cannot be resolved to a type

	at org.graylog.plugins.collector.collectors.CollectorServiceImplTest.testAll(CollectorServiceImplTest.java:99)

testFindById(org.graylog.plugins.collector.collectors.CollectorServiceImplTest)  Time elapsed: 0.025 sec  <<< ERROR!
org.mongojack.MongoJsonMappingException: Error mapping BSON to POJOs
	at org.graylog.plugins.collector.collectors.CollectorServiceImplTest.testFindById(CollectorServiceImplTest.java:119)
Caused by: com.fasterxml.jackson.databind.JsonMappingException:
Can not construct instance of org.graylog.plugins.collector.collectors.CollectorNodeDetails, problem: Unresolved compilation problem:
	AutoValue_CollectorNodeDetails cannot be resolved to a type

 at [Source: N/A; line: -1, column: -1] (through reference chain: org.graylog.plugins.collector.collectors.CollectorImpl["node_details"])
	at org.graylog.plugins.collector.collectors.CollectorServiceImplTest.testFindById(CollectorServiceImplTest.java:119)
Caused by: java.lang.Error:
Unresolved compilation problem:
	AutoValue_CollectorNodeDetails cannot be resolved to a type

	at org.graylog.plugins.collector.collectors.CollectorServiceImplTest.testFindById(CollectorServiceImplTest.java:119)

testSaveFirstRecord(org.graylog.plugins.collector.collectors.CollectorServiceImplTest)  Time elapsed: 0.024 sec  <<< ERROR!
java.lang.Error:
Unresolved compilation problem:

........

```

**Comment by joschi** [comment]
@silenceper Building the plugin works on [Travis CI](https://travis-ci.org/Graylog2/graylog-plugin-collector) and locally on my machine, so there has to be something wrong in your development setup.

If you're using Eclipse, take a look at https://github.com/google/error-prone/issues/305 for a similar problem.

We are using GitHub issues for tracking bugs in Graylog itself, but this doesn't look like one. Please post this issue to our [discussion forum](https://community.graylog.org/) or join the [#graylog channel on freenode IRC](https://webchat.freenode.net/?channels=%23graylog).

Thank you!
